
DB_USER: 
DB_PASSWORD: 
DEFAULT_URL: 
PRODUCTION_URL: 
DEV_URL: 
PORT: '3000'
DEVISE_SECRET_KEY: 
SENDGRID_USERNAME: 
SENDGRID_PASSWORD: 
ADMIN_EMAIL: "admin@mra.com"
ADMIN_PASSWORD: "%26^hj&ujWwe"
CLOUDINARY_USERNAME: 
CLOUDINARY_API_KEY: 
CLOUDINARY_SECRET: 